server {
    listen 5173 default_server;
    server_name _;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}

server {
    listen 5173;
    server_name portal.smartsim.local;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}

server {
    listen 5173;
    server_name crm.smartsim.local;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri /crm.html;
    }
}

server {
    listen 5173;
    server_name inventory.smartsim.local;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri /inventory.html;
    }
}

server {
    listen 5173;
    server_name oms.smartsim.local;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri /oms.html;
    }
}
